import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import Header from '../components/Header';
import SmallCard from '../components/SmallCard';
import styles from '../styles/Home.module.css';

export default function Home({ exploreData }) {
	return (
		<div className=''>
			<Head>
				<title>Adiros AirBnb</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* Header */}
			<Header />
			{/* Banner */}
			<Banner />
			<main className='max-w-7xl mx-auto px-8 sm:px-16'>
				<section className='pt-6'>
					<h2 className='text-4xl font-semibold pb-5'>
						Explore Nearby
					</h2>
					<div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
						{/* Pull data from the server via API endpoint */}
						{exploreData?.map(({ img, distance, location }) => {
							return (
								<SmallCard
									key={img}
									img={img}
									distance={distance}
									location={location}
								/>
							);
						})}
					</div>
				</section>
			</main>
		</div>
	);
}

// Include static site rendering by getting the data from the nextjs server
export async function getStaticProps() {
	const res = await fetch('https://www.jsonkeeper.com/b/4G1G');

	const exploreData = await res.json();

	console.log(exploreData);
	return {
		props: {
			exploreData,
		},
	};
}
